Chapter08/CoreTwitter/Models/ErrorViewModel.cs
using System;

namespace CoreTwitter.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Chapter08/CoreTwitter/Models/TwitterViewModel.cs
using CoreTwitter.Classes;
using System.Collections.Generic;

namespace CoreTwitter.Models
{
    public class TwitterViewModel
    {
        public List<TweetItem> HomeTimelineTweets { get; set; }
    }
}

Chapter08/CoreTwitter/Controllers/HomeController.cs
using CoreTwitter.Classes;
using CoreTwitter.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using Tweetinvi;
using Tweetinvi.Models;

namespace CoreTwitter.Controllers
{
    public class HomeController : Controller
    {
        CoreTwitterConfiguration config;

        public HomeController(IOptions<CoreTwitterConfiguration> options)
        {
            config = options.Value;
        }

        public IActionResult Index()
        {
            try
            {
                if (String.IsNullOrWhiteSpace(config.TwitterConfiguration.Access_Token)) throw new Tweetinvi.Exceptions.TwitterNullCredentialsException();
                if (String.IsNullOrWhiteSpace(config.TwitterConfiguration.Access_Secret)) throw new Tweetinvi.Exceptions.TwitterNullCredentialsException();                                
            }
            catch (Tweetinvi.Exceptions.TwitterNullCredentialsException ex)
            {
                return RedirectToAction("AuthenticateTwitter");
            }
            catch (Exception ex)
            {

            }
            return View();
        }


        public IActionResult AuthenticateTwitter()
        {
            var coreTwitterCredentials = new ConsumerCredentials(
                config.TwitterConfiguration.Consumer_Key
                , config.TwitterConfiguration.Consumer_Secret);
            var callbackURL = "http://" + Request.Host.Value + "/Home/ValidateOAuth";
            var authenticationContext = AuthFlow.InitAuthentication(coreTwitterCredentials, callbackURL);

            return new RedirectResult(authenticationContext.AuthorizationURL);
        }



        public ActionResult ValidateOAuth()
        {
            if (Request.Query.ContainsKey("oauth_verifier") && Request.Query.ContainsKey("authorization_id"))
            {
                var oauthVerifier = Request.Query["oauth_verifier"];
                var authId = Request.Query["authorization_id"];

                var userCredentials = AuthFlow.CreateCredentialsFromVerifierCode(oauthVerifier, authId);
                var twitterUser = Tweetinvi.User.GetAuthenticatedUser(userCredentials);

                config.TwitterConfiguration.Access_Token = userCredentials.AccessToken;
                config.TwitterConfiguration.Access_Secret = userCredentials.AccessTokenSecret;
                
                ViewBag.User = twitterUser;

            }

            return View();
        }


        public IActionResult GetHomeTimeline()
        {
            TwitterViewModel homeView = new TwitterViewModel();

            try
            {
                if (config.TwitterConfiguration.Access_Token == null) throw new Tweetinvi.Exceptions.TwitterNullCredentialsException();
                if (config.TwitterConfiguration.Access_Secret == null) throw new Tweetinvi.Exceptions.TwitterNullCredentialsException();

                var userCredentials = Auth.CreateCredentials(
                    config.TwitterConfiguration.Consumer_Key
                    , config.TwitterConfiguration.Consumer_Secret
                    , config.TwitterConfiguration.Access_Token
                    , config.TwitterConfiguration.Access_Secret);

                var authenticatedUser = Tweetinvi.User.GetAuthenticatedUser(userCredentials);

                IEnumerable<ITweet> twitterFeed = authenticatedUser.GetHomeTimeline(config.TweetFeedLimit);

                List<TweetItem> tweets = new List<TweetItem>();
                foreach(ITweet tweet in twitterFeed)
                {
                    TweetItem tweetItem = new TweetItem();                    

                    tweetItem.Url = tweet.Url;
                    tweets.Add(tweetItem);
                }

                homeView.HomeTimelineTweets = tweets;                
            }
            catch (Tweetinvi.Exceptions.TwitterNullCredentialsException ex)
            {
                return RedirectToAction("AuthenticateTwitter");
            }
            catch (Exception ex)
            {
                
            }

            return View("Views/Twitter/HomeTimeline.cshtml", homeView);
        }


    }
}

Chapter08/CoreTwitter/Controllers/TwitterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreTwitter.Classes;
using Microsoft.AspNetCore.Mvc;
using Tweetinvi;
using Tweetinvi.Models;

namespace CoreTwitter.Controllers
{
    public class TwitterController : Controller
    {        
        public IActionResult ComposeTweet()
        {            
            return View();
        }
        
        public IActionResult PublishTweet(string tweetText)
        {
            var firstTweet = Tweet.PublishTweet(tweetText);
            
            return RedirectToAction("GetHomeTimeline", "Home"); 
        }
    }
}

Chapter08/CoreTwitter/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Chapter08/CoreTwitter/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Chapter08/CoreTwitter/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <p class="lead">TweetCore is an ASP.NET Core MVC application that uses Tweetinvi.</p>
    <p>
        <a href="https://github.com/linvi/tweetinvi" class="btn btn-primary btn-lg">Tweetinvi on Github &raquo;</a>
        <a href="https://www.nuget.org/packages/TweetinviAPI/" class="btn btn-primary btn-lg">Tweetinvi Package on Nuget &raquo;</a>
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Authenticate a User with Twitter</h2>
        <p>
            Tweetinvi allow developers to authenticate Twitter users using URL redirection.
            This process uses 2 steps that can be found on the HomeController. The methods are <b>AuthenticateTwitter</b> and <b>ValidateOAuth</b>.
        </p>
        <p>
            <a class="btn btn-default" href="/Home/AuthenticateTwitter">Try it &raquo;</a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Tweet</h2>
        <p>Learn how to publish tweets, view them on Twitter and delete them! </p>
        <a class="btn btn-default" href="/Tweet">Try it &raquo;</a>
    </div>
    <div class="col-md-4">
        <h2>Stream with ASP.NET</h2>
        <p>Soon you will be able to access examples to access streams from a Website. </p>
        <p><a class="btn btn-default disabled">Try it &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Timeline</h2>
        <p>Display a specific user timeline,</p>
        <p><a class="btn btn-default disabled">Try it &raquo;</a></p>
    </div>
</div>

Chapter08/CoreTwitter/Views/Home/ValidateOAuth.cshtml
@if (@ViewBag.User != null)
{
    <h2>OAuth Authentication Succeeded!</h2>
    <p>Welcome to the CoreTwitter Demo Application <b>@ViewBag.User.Name</b>. You have been successfully authenticated via Twitter.</p>

    <div class="row">
        <div class="col-md-4">
            <h2>Go to your home feed</h2>
            <p>
                See what's new on your home feed.
            </p>
            <p>
                <a class="btn btn-default" href="/Home/GetHomeTimeline">Home &raquo;</a>
            </p>
        </div>
    </div>
}
else
{
    <h2>OAuth Authentication failed!</h2>
    <p>An error occurred during authentication. Try <a href="/Home/TwitterAuth">authenticating</a> again.</p>
}

Chapter08/CoreTwitter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreTwitter</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <link href="~/css/site.css" rel="stylesheet" type="text/css" />

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CoreTwitter</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="GetHomeTimeline">Timeline</a></li>
                    <li><a asp-area="" asp-controller="Twitter" asp-action="ComposeTweet">Tweet</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - CoreTwitter</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>